### ISSUE TITLE
What versions of Tensorflow and Keras are needed?

### ISSUE THREAD

**Issue by Crista23** [CyberZHG/keras-word-char-embd#4]
The code crashes in Tensorflow 1.4 with the error below:

Get train data entries...
Train: 1000  Validate: 250
Get dictionaries....
Create model...
Traceback (most recent call last):
  File "sentiment_analysis.py", line 69, in <module>
    char_hidden_layer_type='lstm'
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras_wc_embd/wrapper.py", line 122, in get_embedding_layer
    char_mask_zero=char_mask_zero)
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras_wc_embd/word_char_embd.py", line 123, in get_embedding_layer
    return_state=False,
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras/layers/recurrent.py", line 949, in __init__
    super(LSTM, self).__init__(**kwargs)
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras/layers/recurrent.py", line 191, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 281, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'return_state')

**Comment by Crista23** [comment]
Also tried running it with Tensorflow 0.11 backend and crashes too:

Get train data entries...
Train: 1000  Validate: 250
Get dictionaries....
Create model...
Traceback (most recent call last):
  File "sentiment_analysis.py", line 69, in <module>
    char_hidden_layer_type='lstm'
  File "/home/user/tf_hybrid/lib/python2.7/site-packages/keras_wc_embd/wrapper.py", line 122, in get_embedding_layer
    char_mask_zero=char_mask_zero)
  File "/home/user/tf_hybrid/lib/python2.7/site-packages/keras_wc_embd/word_char_embd.py", line 108, in get_embedding_layer
    )(word_input_layer)
  File "/home/user/tf_hybrid/lib/python2.7/site-packages/keras/engine/base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/user/tf_hybrid/lib/python2.7/site-packages/keras/engine/base_layer.py", line 279, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "/home/user/tf_hybrid/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 472, in is_keras_tensor
    if not is_tensor(x):
  File "/home/user/tf_hybrid/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 480, in is_tensor
    return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
AttributeError: 'module' object has no attribute '_TensorLike'

**Comment by CyberZHG** [comment]
I guess you are using an outdated version of Keras.
